export { XUIProvider } from './theme-context'
export { useColorMode, useXUITheme, useXUIColors } from './theme-hooks'
export { defaultDarkTheme, defaultTheme } from '@xaui/core/theme'
export type { PartialXUITheme as XUITheme } from '@xaui/core/theme'
export { colors as palette } from '@xaui/core/palette'
export { Portal, PortalHost } from './portal'
