export { XUIProvider } from './theme-context'
export { useColorMode, useXUITheme, useXUIColors } from './theme-hooks'
export { defaultDarkTheme, defaultTheme } from '@xaui/core/theme'
export type { XUITheme } from '@xaui/core/theme'
export { Portal, PortalHost } from './portal'
