import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import prettier from 'prettier'
import { deriveColors } from '../../packages/native/src/theme/derive-colors'
import { contrastRatio } from '../../packages/native/src/utils/colors'
import { CONTRAST_FLOOR, contrastPairs, primitives, source } from './source'
import type { ColorMode } from '../../packages/native/src/theme/theme.type'

const root = join(dirname(fileURLToPath(import.meta.url)), '../..')
const targets = [
  join(root, 'packages/native/src/theme/tokens.gen.ts'),
  join(root, 'packages/hybrid/src/theme/tokens.gen.ts'),
]

const modes: ColorMode[] = ['light', 'dark']

function resolveColors(mode: ColorMode) {
  const s = source[mode]
  return { ...s, ...deriveColors(s), ...primitives }
}

/** Both modes must expose the same keys — a one-sided token is a build error, not an
 * `undefined` in production. */
function assertKeyParity(colors: Record<ColorMode, Record<string, string>>) {
  const light = Object.keys(colors.light).sort()
  const dark = Object.keys(colors.dark).sort()
  const onlyLight = light.filter(k => !dark.includes(k))
  const onlyDark = dark.filter(k => !light.includes(k))
  if (onlyLight.length === 0 && onlyDark.length === 0) return
  throw new Error(
    `Token keys differ between modes.\n  only in light: ${onlyLight.join(', ') || '—'}\n  only in dark: ${onlyDark.join(', ') || '—'}`
  )
}

/** Every X / XForeground pair must clear the floor in both modes. */
function assertContrast() {
  const failures: string[] = []
  for (const mode of modes) {
    const s = source[mode]
    for (const [a, b] of contrastPairs) {
      const ratio = contrastRatio(s[a], s[b])
      if (ratio < CONTRAST_FLOOR) {
        failures.push(`  ${mode}: ${a} / ${b} = ${ratio.toFixed(2)}`)
      }
    }
  }
  if (failures.length === 0) return
  throw new Error(
    `Contrast below ${CONTRAST_FLOOR}:\n${failures.join('\n')}\n` +
      'Adjust the source colour rather than lowering the floor.'
  )
}

async function render(colors: Record<ColorMode, Record<string, string>>) {
  const body = modes
    .map(
      mode =>
        `  ${mode}: {\n` +
        Object.entries(colors[mode])
          .map(([key, value]) => `    ${key}: '${value}',`)
          .join('\n') +
        '\n  },'
    )
    .join('\n')

  const keys = Object.keys(source.light)
    .map(key => `  '${key}',`)
    .join('\n')

  const file = `// Generated by tooling/tokens/generate.ts — do not edit.
// Change tooling/tokens/source.ts and run \`pnpm tokens:generate\`.

export const tokens = {
${body}
} as const

/** Which keys belong to the source layer — the rest is derived or primitive. */
export const sourceKeys = [
${keys}
] as const
`
  return prettier.format(file, {
    ...(await prettier.resolveConfig(targets[0])),
    parser: 'typescript',
  })
}

async function main() {
  const check = process.argv.includes('--check')
  const colors = { light: resolveColors('light'), dark: resolveColors('dark') }

  assertKeyParity(colors)
  assertContrast()

  const content = await render(colors)
  const stale: string[] = []

  for (const target of targets) {
    if (check) {
      const current = await readFile(target, 'utf8').catch(() => null)
      if (current !== content) stale.push(relative(root, target))
      continue
    }
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, content)
  }

  if (stale.length > 0) {
    throw new Error(
      `Generated tokens are out of date:\n${stale.map(f => `  ${f}`).join('\n')}\n` +
        'Run `pnpm tokens:generate` and commit the result.'
    )
  }

  const count = Object.keys(colors.light).length
  const action = check ? 'checked' : 'wrote'
  process.stdout.write(`${action} ${count} colour tokens per mode\n`)
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
  process.exitCode = 1
})
